#!/usr/bin/env sh
 
set -e
 
function clean { 
  echo "taking down zuul test server"
  kill $! 
}
 
trap clean INT TERM ERR
 
# assuming zuul and mocha phantomjs are installed as devDependencies of this module
npm run local &
node_modules/.bin/mocha-phantomjs http://localhost:1337/__zuul
 
clean
